# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tlf < Formula
  desc ""
  homepage "https://github.com/thegeorgejoseph/tlf"
  version "1.0.0"

  on_macos do
    url "https://github.com/thegeorgejoseph/tlf/releases/download/v1.0.0/tlf_Darwin_all.tar.gz"
    sha256 "43be9490dfd2a8982cd6514b8223795eb7fb971860c038717dde6d7fe9fa1444"

    def install
      bin.install "tlf"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thegeorgejoseph/tlf/releases/download/v1.0.0/tlf_Linux_arm64.tar.gz"
      sha256 "d7545d290fd3c5cd045d686d94191aaf41bfb9fe0abc80e1a5b0e0b8390624bc"

      def install
        bin.install "tlf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thegeorgejoseph/tlf/releases/download/v1.0.0/tlf_Linux_x86_64.tar.gz"
      sha256 "baed9588b85e6e18994a59d1b3c9a75732e155f5734ed89a638d3912cc70da03"

      def install
        bin.install "tlf"
      end
    end
  end
end
